# Generated by Django 4.2.4 on 2024-11-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisee',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='f-profile_images/'),
        ),
        migrations.AlterField(
            model_name='franchisee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchasee', to='demo1.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
