# Generated by Django 4.2.4 on 2024-11-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo1', '0002_alter_franchisee_profile_image_alter_franchisee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchasees', to='demo1.user'),
        ),
    ]
